import type { NextPage } from "next";
import Head from "next/head";
import { Button } from "../components/button";
import Select from "~/components/select";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto">
        <h1 className="text-5xl font-semibold pb-10">Mockup of Radix UI</h1>

        <div className="flex flex-col space-y-4">-</div>

        <table className="table-fixed border border-slate-500 w-full">
          <thead>
            <tr>
              <th className="border border-slate-600">Field 1</th>
              <th className="border border-slate-600">Field 2</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td className="border border-slate-700">Value 1</td>
              <td className="border border-slate-700">
                <Select />
              </td>
            </tr>
          </tbody>
        </table>
      </main>

      <footer className="">
        <Button>Click here</Button>
      </footer>
    </div>
  );
};

export default Home;
